services:
  - type: web
    name: cartoon-generator
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python cartoon_app.py"
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false